import "./globals.css";
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import NavbarProvider from "./Navbar/NavbarProvider";

const sourceCode = Source_Code_Pro({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Ajay.Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sourceCode.className}>
        <NavbarProvider>{children}</NavbarProvider>
      </body>
    </html>
  );
}
